# This is a basic workflow to help you get started with Actions

name: Build OE

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      # Runs a set of commands using the runners shell
      - name: Build OE
        run: |
          git clone git://git.openembedded.org/openembedded-core oe-core
          cd oe-core
          git clone git://git.openembedded.org/bitbake bitbake
          git checkout hardknott
          cd bitbake
          git checkout 1.50
          cd ..
          source ./oe-init-build-env
          sed -i 's/#MACHINE ?= "qemux86"/MACHINE ?= "qemux86"/g' ./conf/local.conf
          bitbake core-image-minimal
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: oe-core-minimal
          path: oe-core/build/
          retention-days: 30
