# This is a basic workflow to help you get started with Actions

name: Get Changed Files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          for file in ${files[@]}; do
            echo "All: ${file}."
          done
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for file in ${files[@]}; do
            echo "Added: ${file}."
          done
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.deleted }}')"
          for file in ${files[@]}; do
            echo "Deleted: ${file}."
          done
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.renamed }}')"
          for file in ${files[@]}; do
            echo "Renamed: ${file}."
          done
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.modified }}')"
          for file in ${files[@]}; do
            echo "Modified: ${file}."
          done
